global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    metrics_path: /metrics  # RabbitMQ metrics path
    scrape_interval: 15s
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']